//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomUrl {
            get {
                return ((string)(this["ZoomUrl"]));
            }
            set {
                this["ZoomUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int ZoomHours {
            get {
                return ((int)(this["ZoomHours"]));
            }
            set {
                this["ZoomHours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int ZoomMinutes {
            get {
                return ((int)(this["ZoomMinutes"]));
            }
            set {
                this["ZoomMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ZoomOnOff {
            get {
                return ((bool)(this["ZoomOnOff"]));
            }
            set {
                this["ZoomOnOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName1_1 {
            get {
                return ((string)(this["LectureName1_1"]));
            }
            set {
                this["LectureName1_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName1_2 {
            get {
                return ((string)(this["LectureName1_2"]));
            }
            set {
                this["LectureName1_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName1_3 {
            get {
                return ((string)(this["LectureName1_3"]));
            }
            set {
                this["LectureName1_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName1_4 {
            get {
                return ((string)(this["LectureName1_4"]));
            }
            set {
                this["LectureName1_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName1_5 {
            get {
                return ((string)(this["LectureName1_5"]));
            }
            set {
                this["LectureName1_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName2_1 {
            get {
                return ((string)(this["LectureName2_1"]));
            }
            set {
                this["LectureName2_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName2_2 {
            get {
                return ((string)(this["LectureName2_2"]));
            }
            set {
                this["LectureName2_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName2_3 {
            get {
                return ((string)(this["LectureName2_3"]));
            }
            set {
                this["LectureName2_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName2_4 {
            get {
                return ((string)(this["LectureName2_4"]));
            }
            set {
                this["LectureName2_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName2_5 {
            get {
                return ((string)(this["LectureName2_5"]));
            }
            set {
                this["LectureName2_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName3_1 {
            get {
                return ((string)(this["LectureName3_1"]));
            }
            set {
                this["LectureName3_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName3_2 {
            get {
                return ((string)(this["LectureName3_2"]));
            }
            set {
                this["LectureName3_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName3_3 {
            get {
                return ((string)(this["LectureName3_3"]));
            }
            set {
                this["LectureName3_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName3_4 {
            get {
                return ((string)(this["LectureName3_4"]));
            }
            set {
                this["LectureName3_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName3_5 {
            get {
                return ((string)(this["LectureName3_5"]));
            }
            set {
                this["LectureName3_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName4_1 {
            get {
                return ((string)(this["LectureName4_1"]));
            }
            set {
                this["LectureName4_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName4_2 {
            get {
                return ((string)(this["LectureName4_2"]));
            }
            set {
                this["LectureName4_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName4_3 {
            get {
                return ((string)(this["LectureName4_3"]));
            }
            set {
                this["LectureName4_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName4_4 {
            get {
                return ((string)(this["LectureName4_4"]));
            }
            set {
                this["LectureName4_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName4_5 {
            get {
                return ((string)(this["LectureName4_5"]));
            }
            set {
                this["LectureName4_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName5_1 {
            get {
                return ((string)(this["LectureName5_1"]));
            }
            set {
                this["LectureName5_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName5_2 {
            get {
                return ((string)(this["LectureName5_2"]));
            }
            set {
                this["LectureName5_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName5_3 {
            get {
                return ((string)(this["LectureName5_3"]));
            }
            set {
                this["LectureName5_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName5_4 {
            get {
                return ((string)(this["LectureName5_4"]));
            }
            set {
                this["LectureName5_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LectureName5_5 {
            get {
                return ((string)(this["LectureName5_5"]));
            }
            set {
                this["LectureName5_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL1_1 {
            get {
                return ((string)(this["ZoomURL1_1"]));
            }
            set {
                this["ZoomURL1_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL1_2 {
            get {
                return ((string)(this["ZoomURL1_2"]));
            }
            set {
                this["ZoomURL1_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL1_3 {
            get {
                return ((string)(this["ZoomURL1_3"]));
            }
            set {
                this["ZoomURL1_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL1_4 {
            get {
                return ((string)(this["ZoomURL1_4"]));
            }
            set {
                this["ZoomURL1_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL1_5 {
            get {
                return ((string)(this["ZoomURL1_5"]));
            }
            set {
                this["ZoomURL1_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL2_1 {
            get {
                return ((string)(this["ZoomURL2_1"]));
            }
            set {
                this["ZoomURL2_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL2_2 {
            get {
                return ((string)(this["ZoomURL2_2"]));
            }
            set {
                this["ZoomURL2_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL2_3 {
            get {
                return ((string)(this["ZoomURL2_3"]));
            }
            set {
                this["ZoomURL2_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL2_4 {
            get {
                return ((string)(this["ZoomURL2_4"]));
            }
            set {
                this["ZoomURL2_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL2_5 {
            get {
                return ((string)(this["ZoomURL2_5"]));
            }
            set {
                this["ZoomURL2_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL3_1 {
            get {
                return ((string)(this["ZoomURL3_1"]));
            }
            set {
                this["ZoomURL3_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL3_2 {
            get {
                return ((string)(this["ZoomURL3_2"]));
            }
            set {
                this["ZoomURL3_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL3_3 {
            get {
                return ((string)(this["ZoomURL3_3"]));
            }
            set {
                this["ZoomURL3_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL3_4 {
            get {
                return ((string)(this["ZoomURL3_4"]));
            }
            set {
                this["ZoomURL3_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL3_5 {
            get {
                return ((string)(this["ZoomURL3_5"]));
            }
            set {
                this["ZoomURL3_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL4_1 {
            get {
                return ((string)(this["ZoomURL4_1"]));
            }
            set {
                this["ZoomURL4_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL4_2 {
            get {
                return ((string)(this["ZoomURL4_2"]));
            }
            set {
                this["ZoomURL4_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL4_3 {
            get {
                return ((string)(this["ZoomURL4_3"]));
            }
            set {
                this["ZoomURL4_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL4_4 {
            get {
                return ((string)(this["ZoomURL4_4"]));
            }
            set {
                this["ZoomURL4_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL4_5 {
            get {
                return ((string)(this["ZoomURL4_5"]));
            }
            set {
                this["ZoomURL4_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL5_1 {
            get {
                return ((string)(this["ZoomURL5_1"]));
            }
            set {
                this["ZoomURL5_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL5_2 {
            get {
                return ((string)(this["ZoomURL5_2"]));
            }
            set {
                this["ZoomURL5_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL5_3 {
            get {
                return ((string)(this["ZoomURL5_3"]));
            }
            set {
                this["ZoomURL5_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL5_4 {
            get {
                return ((string)(this["ZoomURL5_4"]));
            }
            set {
                this["ZoomURL5_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZoomURL5_5 {
            get {
                return ((string)(this["ZoomURL5_5"]));
            }
            set {
                this["ZoomURL5_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("08")]
        public string Time1_0_h {
            get {
                return ((string)(this["Time1_0_h"]));
            }
            set {
                this["Time1_0_h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string Time1_0_m {
            get {
                return ((string)(this["Time1_0_m"]));
            }
            set {
                this["Time1_0_m"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string Time1_1_h {
            get {
                return ((string)(this["Time1_1_h"]));
            }
            set {
                this["Time1_1_h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string Time1_1_m {
            get {
                return ((string)(this["Time1_1_m"]));
            }
            set {
                this["Time1_1_m"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string Time2_0_h {
            get {
                return ((string)(this["Time2_0_h"]));
            }
            set {
                this["Time2_0_h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string Time2_0_m {
            get {
                return ((string)(this["Time2_0_m"]));
            }
            set {
                this["Time2_0_m"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public string Time2_1_h {
            get {
                return ((string)(this["Time2_1_h"]));
            }
            set {
                this["Time2_1_h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00")]
        public string Time2_1_m {
            get {
                return ((string)(this["Time2_1_m"]));
            }
            set {
                this["Time2_1_m"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public string Time3_0_h {
            get {
                return ((string)(this["Time3_0_h"]));
            }
            set {
                this["Time3_0_h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00")]
        public string Time3_0_m {
            get {
                return ((string)(this["Time3_0_m"]));
            }
            set {
                this["Time3_0_m"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public string Time3_1_h {
            get {
                return ((string)(this["Time3_1_h"]));
            }
            set {
                this["Time3_1_h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string Time3_1_m {
            get {
                return ((string)(this["Time3_1_m"]));
            }
            set {
                this["Time3_1_m"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public string Time4_0_h {
            get {
                return ((string)(this["Time4_0_h"]));
            }
            set {
                this["Time4_0_h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public string Time4_0_m {
            get {
                return ((string)(this["Time4_0_m"]));
            }
            set {
                this["Time4_0_m"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public string Time4_1_h {
            get {
                return ((string)(this["Time4_1_h"]));
            }
            set {
                this["Time4_1_h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string Time4_1_m {
            get {
                return ((string)(this["Time4_1_m"]));
            }
            set {
                this["Time4_1_m"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public string Time5_0_h {
            get {
                return ((string)(this["Time5_0_h"]));
            }
            set {
                this["Time5_0_h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string Time5_0_m {
            get {
                return ((string)(this["Time5_0_m"]));
            }
            set {
                this["Time5_0_m"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public string Time5_1_h {
            get {
                return ((string)(this["Time5_1_h"]));
            }
            set {
                this["Time5_1_h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string Time5_1_m {
            get {
                return ((string)(this["Time5_1_m"]));
            }
            set {
                this["Time5_1_m"] = value;
            }
        }
    }
}
